### PR TITLE
Filter out duplicate entries over multiple result sets

### PR DESCRIPTION
**Pull request by ramonvansparrentak**

### CODE REVIEW

**Comment by korydraughn** [comment]
@ramonvansparrentak Any updates on this? Are you waiting on us for anything?

**Comment by trel** [comment]
I think this is 'ready'... it's the last issue in the 4.3.4.0 release target.

**Comment by korydraughn** [comment]
Yeah, it's been open for months now. I'll look at providing a test for this and getting it merged.

**Comment by korydraughn** [comment]
I have not been able to reproduce the issue.

We need a test that confirms the issue is real.

**Comment by korydraughn** [comment]
I now have a test which demonstrates the issue.

Testing this fix now.

**Comment by korydraughn** [comment]
Superseded by #470.

@ramonvansparrentak's work is included in the other PR. They will still get credit for the work.

Closing.

**Pull request closed without merging**
